# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - unnecessary_new
    - prefer_final_fields
    - always_specify_types
    - public_member_api_docs
    - lines_longer_than_80_chars: false